---
- name: Install kexec-tools
  package:
    name: kexec-tools
    state: present

- name: Find out reserved memory for the crash kernel
  slurp:
    src: /sys/kernel/kexec_crash_size
  register: kexec_crash_size

- include_tasks: ssh.yml
  when:
    - kdump_target
    - kdump_target.type == "ssh"

- name: Generate /etc/kdump.conf
  template:
    src: kdump.conf.j2
    dest: /etc/kdump.conf
    backup: yes
  when: kexec_crash_size.content|b64decode|int > 0
  notify: restart kdump

- name: Generate /etc/sysconfig/kdump
  template:
    src: kdump.j2
    dest: /etc/sysconfig/kdump
    backup: yes
  when: kexec_crash_size.content|b64decode|int > 0
  notify: restart kdump
