---
- hosts: all
  pre_tasks:
    - name: Display all parameters known for the Foreman host
      debug:
        var: foreman
  tasks:
    - name: Apply roles
      include_role:
        name: "{{ role }}"
      loop: "{{ foreman_ansible_roles }}"
      loop_control:
        loop_var: role
