---
- name: Set version specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: define an empty list of pools to be used in testing
  set_fact:
    _storage_pools_list: []

- name: define an empty list of volumes to be used in testing
  set_fact:
    _storage_volumes_list: []

- name: include the appropriate provider tasks
  include_tasks: "main-{{ storage_provider }}.yml"
